name: Auto-update zoomrecovery.rb on new release

on:
  repository_dispatch:
    types: [release-trigger]

jobs:
  update-formula:
    runs-on: macos-latest

    steps:
      - name: Clone tap repo
        uses: actions/checkout@v3

      - name: Fetch latest release tag from ZoomRecovery
        id: get_tag
        run: |
          TAG=$(curl -s https://api.github.com/repos/twinboi90/ZoomRecovery/releases/latest | jq -r .tag_name)
          echo "Latest tag is: $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Download release tarball and compute SHA256
        id: compute_sha
        run: |
          TAG=${{ steps.get_tag.outputs.tag }}
          TARBALL_URL="https://github.com/twinboi90/ZoomRecovery/archive/refs/tags/${TAG}.tar.gz"
          echo "Tarball URL: $TARBALL_URL"

          curl -L -o zoomrecovery.tar.gz "$TARBALL_URL"

          SHA256=$(shasum -a 256 zoomrecovery.tar.gz | awk '{print $1}')
          echo "SHA256: $SHA256"
          echo "sha256=$SHA256" >> $GITHUB_OUTPUT
          echo "url=$TARBALL_URL" >> $GITHUB_OUTPUT

      - name: Update Formula
        run: |
          FORMULA="Formula/zoomrecovery.rb"

          # Update the URL
          sed -i '' "s|url \".*\"|url \"${{ steps.compute_sha.outputs.url }}\"|" "$FORMULA"

          # Update the SHA256
          sed -i '' "s|sha256 \".*\"|sha256 \"${{ steps.compute_sha.outputs.sha256 }}\"|" "$FORMULA"

      - name: Commit and push formula update
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git add Formula/zoomrecovery.rb
          git commit -m "Update zoomrecovery.rb to ${{ steps.get_tag.outputs.tag }}"
          git push origin main
