name: Auto-update zoomrecovery.rb on new release

on:
  repository_dispatch:
    types: [release-trigger]

jobs:
  update-formula:
    runs-on: macos-latest

    steps:
      - name: Clone tap repo
        uses: actions/checkout@v3

      - name: Fetch latest release tag from ZoomRecovery
        id: release
        run: |
          TAG=$(curl -s https://api.github.com/repos/twinboi90/ZoomRecovery/releases/latest | jq -r .tag_name)
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Download tarball and compute SHA256
        run: |
          TAG=${{ steps.release.outputs.tag }}
          curl -L -o zoomrecovery.tar.gz "https://github.com/twinboi90/ZoomRecovery/archive/refs/tags/$TAG.tar.gz"
          SHA256=$(shasum -a 256 zoomrecovery.tar.gz | awk '{print $1}')
          echo "sha256=$SHA256" >> $GITHUB_ENV
          echo "tag=$TAG" >> $GITHUB_ENV

      - name: Update Formula
        run: |
          FORMULA="Formula/zoomrecovery.rb"
          sed -i '' "s|url \".*\"|url \"https://github.com/twinboi90/ZoomRecovery/archive/refs/tags/$tag.tar.gz\"|" "$FORMULA"
          sed -i '' "s|sha256 \".*\"|sha256 \"$sha256\"|" "$FORMULA"

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Formula/zoomrecovery.rb
          git commit -m "Update zoomrecovery.rb to $tag"
          git push origin main
